# LLVM 23.1.1 paired static C++ runtimes. Load with cmake -C this-file.
# The bootstrap compiler, target/sysroot, Python and Ninja remain caller inputs.
set(CMAKE_BUILD_TYPE Release CACHE STRING "Runtime build mode")
set(CMAKE_POSITION_INDEPENDENT_CODE ON CACHE BOOL "Static archives usable by LLVM/app")
set(LLVM_ENABLE_RUNTIMES "libunwind;libcxxabi;libcxx" CACHE STRING "Paired runtime projects")
set(LLVM_ENABLE_PER_TARGET_RUNTIME_DIR OFF CACHE BOOL "One explicitly bound target per build")
set(LLVM_INCLUDE_TESTS OFF CACHE BOOL "No vendored upstream test suites")
set(LLVM_INCLUDE_DOCS OFF CACHE BOOL "No vendored upstream documentation")
set(LLVM_ENABLE_SPHINX OFF CACHE BOOL "No documentation generator")
set(LLVM_ENABLE_DOXYGEN OFF CACHE BOOL "No documentation generator")
set(LIBCXX_INCLUDE_TESTS OFF CACHE BOOL "No test/ABI-list subtree")
set(LIBCXX_INCLUDE_DOCS OFF CACHE BOOL "No docs subtree")
set(LIBCXX_INCLUDE_BENCHMARKS OFF CACHE BOOL "No benchmark subtree")
set(LIBCXXABI_INCLUDE_TESTS OFF CACHE BOOL "No test/fuzz subtree")
set(LIBUNWIND_INCLUDE_TESTS OFF CACHE BOOL "No test subtree")
set(LIBUNWIND_INCLUDE_DOCS OFF CACHE BOOL "No docs subtree")
set(LIBCXX_ENABLE_SHARED OFF CACHE BOOL "Single static provider")
set(LIBCXX_ENABLE_STATIC ON CACHE BOOL "Paired libc++ archive")
set(LIBCXXABI_ENABLE_SHARED OFF CACHE BOOL "Single static provider")
set(LIBCXXABI_ENABLE_STATIC ON CACHE BOOL "Paired C++ ABI archive")
set(LIBUNWIND_ENABLE_SHARED OFF CACHE BOOL "Single static provider")
set(LIBUNWIND_ENABLE_STATIC ON CACHE BOOL "Paired unwinder archive")
set(LIBCXX_CXX_ABI libcxxabi CACHE STRING "Use this paired ABI library")
set(LIBCXXABI_USE_LLVM_UNWINDER ON CACHE BOOL "Use this paired LLVM unwinder")
set(LIBCXXABI_ENABLE_STATIC_UNWINDER ON CACHE BOOL "Link the static unwinder target")
set(LIBCXX_STATICALLY_LINK_ABI_IN_STATIC_LIBRARY OFF CACHE BOOL "Keep three separate archives")
set(LIBCXXABI_STATICALLY_LINK_UNWINDER_IN_STATIC_LIBRARY OFF CACHE BOOL "Keep three separate archives")
set(LIBCXX_ABI_VERSION 1 CACHE STRING "Stable libc++ ABI")
set(LIBCXX_ABI_NAMESPACE __1 CACHE STRING "Stable ABI namespace")
set(LIBCXX_ABI_UNSTABLE OFF CACHE BOOL "Stable ABI configuration")
set(LIBCXX_HARDENING_MODE none CACHE STRING "VM checks remain independent of libc++ hardening")
set(LIBCXX_ENABLE_EXCEPTIONS ON CACHE BOOL "Real VM C++ exception propagation")
set(LIBCXX_ENABLE_RTTI ON CACHE BOOL "Match LLVM/app ABI")
set(LIBCXX_ENABLE_THREADS ON CACHE BOOL "VM-managed and runtime threads")
set(LIBCXXABI_ENABLE_EXCEPTIONS ON CACHE BOOL "Real C++ EH")
# libc++abi has no separate ENABLE_RTTI CMake option in this release.
set(LIBCXXABI_ENABLE_THREADS ON CACHE BOOL "Runtime threading")
set(LIBUNWIND_ENABLE_THREADS ON CACHE BOOL "Concurrent runtime unwind safety")
# Release alone does not disable these independently default-on assertions.
set(LIBCXXABI_ENABLE_ASSERTIONS OFF CACHE BOOL "Release ABI runtime")
set(LIBUNWIND_ENABLE_ASSERTIONS OFF CACHE BOOL "Release unwinder without debug trace checks")
# Preserve upstream frame-registration/architecture algorithms. No cache,
# cross-unwind, shadow-stack or foreign-platform provider policy is inferred.
