/*************************************************************
 * UlteSoft WebAssembly Virtual Machine (Version 2)            *
 * Licensed under the APL-2.0 License (see LICENSE file).      *
 *************************************************************/
#pragma once

#if defined(UWVM_RUNTIME_LLVM_JIT)
// Shared non-macro constants are also used by object-graph validation on
// other hosts. Preserve the same header shielding and restore caller macros.
// Windows SDK headers define IMAGE_* names as macros; LLVM declares the same
// COFF names as C++ constants. A consumer may already have included winnt.h.
// Isolate the complete IMAGE_* vocabulary of LLVM BinaryFormat/Object COFF
// while parsing both headers, then restore EVERY prior macro definition.
// This wrapper belongs in named modules' global fragments too. It changes
// no endian, host ABI, allocation, executable image or unwind-table policy.
// The static list is source-reviewed against the bundled LLVM 23 headers.
#pragma push_macro("IMAGE_AUX_SYMBOL_TYPE_TOKEN_DEF")
#undef IMAGE_AUX_SYMBOL_TYPE_TOKEN_DEF
#pragma push_macro("IMAGE_COMDAT_SELECT_ANY")
#undef IMAGE_COMDAT_SELECT_ANY
#pragma push_macro("IMAGE_COMDAT_SELECT_ASSOCIATIVE")
#undef IMAGE_COMDAT_SELECT_ASSOCIATIVE
#pragma push_macro("IMAGE_COMDAT_SELECT_EXACT_MATCH")
#undef IMAGE_COMDAT_SELECT_EXACT_MATCH
#pragma push_macro("IMAGE_COMDAT_SELECT_LARGEST")
#undef IMAGE_COMDAT_SELECT_LARGEST
#pragma push_macro("IMAGE_COMDAT_SELECT_NEWEST")
#undef IMAGE_COMDAT_SELECT_NEWEST
#pragma push_macro("IMAGE_COMDAT_SELECT_NODUPLICATES")
#undef IMAGE_COMDAT_SELECT_NODUPLICATES
#pragma push_macro("IMAGE_COMDAT_SELECT_SAME_SIZE")
#undef IMAGE_COMDAT_SELECT_SAME_SIZE
#pragma push_macro("IMAGE_DEBUG_TYPE_BORLAND")
#undef IMAGE_DEBUG_TYPE_BORLAND
#pragma push_macro("IMAGE_DEBUG_TYPE_CLSID")
#undef IMAGE_DEBUG_TYPE_CLSID
#pragma push_macro("IMAGE_DEBUG_TYPE_CODEVIEW")
#undef IMAGE_DEBUG_TYPE_CODEVIEW
#pragma push_macro("IMAGE_DEBUG_TYPE_COFF")
#undef IMAGE_DEBUG_TYPE_COFF
#pragma push_macro("IMAGE_DEBUG_TYPE_EXCEPTION")
#undef IMAGE_DEBUG_TYPE_EXCEPTION
#pragma push_macro("IMAGE_DEBUG_TYPE_EX_DLLCHARACTERISTICS")
#undef IMAGE_DEBUG_TYPE_EX_DLLCHARACTERISTICS
#pragma push_macro("IMAGE_DEBUG_TYPE_FIXUP")
#undef IMAGE_DEBUG_TYPE_FIXUP
#pragma push_macro("IMAGE_DEBUG_TYPE_FPO")
#undef IMAGE_DEBUG_TYPE_FPO
#pragma push_macro("IMAGE_DEBUG_TYPE_ILTCG")
#undef IMAGE_DEBUG_TYPE_ILTCG
#pragma push_macro("IMAGE_DEBUG_TYPE_MISC")
#undef IMAGE_DEBUG_TYPE_MISC
#pragma push_macro("IMAGE_DEBUG_TYPE_MPX")
#undef IMAGE_DEBUG_TYPE_MPX
#pragma push_macro("IMAGE_DEBUG_TYPE_OMAP_FROM_SRC")
#undef IMAGE_DEBUG_TYPE_OMAP_FROM_SRC
#pragma push_macro("IMAGE_DEBUG_TYPE_OMAP_TO_SRC")
#undef IMAGE_DEBUG_TYPE_OMAP_TO_SRC
#pragma push_macro("IMAGE_DEBUG_TYPE_POGO")
#undef IMAGE_DEBUG_TYPE_POGO
#pragma push_macro("IMAGE_DEBUG_TYPE_REPRO")
#undef IMAGE_DEBUG_TYPE_REPRO
#pragma push_macro("IMAGE_DEBUG_TYPE_RESERVED10")
#undef IMAGE_DEBUG_TYPE_RESERVED10
#pragma push_macro("IMAGE_DEBUG_TYPE_UNKNOWN")
#undef IMAGE_DEBUG_TYPE_UNKNOWN
#pragma push_macro("IMAGE_DEBUG_TYPE_VC_FEATURE")
#undef IMAGE_DEBUG_TYPE_VC_FEATURE
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_APPCONTAINER")
#undef IMAGE_DLL_CHARACTERISTICS_APPCONTAINER
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_DYNAMIC_BASE")
#undef IMAGE_DLL_CHARACTERISTICS_DYNAMIC_BASE
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_EX_CET_COMPAT")
#undef IMAGE_DLL_CHARACTERISTICS_EX_CET_COMPAT
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_EX_CET_COMPAT_STRICT_MODE")
#undef IMAGE_DLL_CHARACTERISTICS_EX_CET_COMPAT_STRICT_MODE
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_EX_CET_DYNAMIC_APIS_ALLOW_IN_PROC_ONLY")
#undef IMAGE_DLL_CHARACTERISTICS_EX_CET_DYNAMIC_APIS_ALLOW_IN_PROC_ONLY
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_EX_CET_RESERVED_1")
#undef IMAGE_DLL_CHARACTERISTICS_EX_CET_RESERVED_1
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_EX_CET_RESERVED_2")
#undef IMAGE_DLL_CHARACTERISTICS_EX_CET_RESERVED_2
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_EX_CET_SET_CONTEXT_IP_VALIDATION_RELAXED_MODE")
#undef IMAGE_DLL_CHARACTERISTICS_EX_CET_SET_CONTEXT_IP_VALIDATION_RELAXED_MODE
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_EX_FORWARD_CFI_COMPAT")
#undef IMAGE_DLL_CHARACTERISTICS_EX_FORWARD_CFI_COMPAT
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_EX_HOTPATCH_COMPATIBLE")
#undef IMAGE_DLL_CHARACTERISTICS_EX_HOTPATCH_COMPATIBLE
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_FORCE_INTEGRITY")
#undef IMAGE_DLL_CHARACTERISTICS_FORCE_INTEGRITY
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_GUARD_CF")
#undef IMAGE_DLL_CHARACTERISTICS_GUARD_CF
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_HIGH_ENTROPY_VA")
#undef IMAGE_DLL_CHARACTERISTICS_HIGH_ENTROPY_VA
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_NO_BIND")
#undef IMAGE_DLL_CHARACTERISTICS_NO_BIND
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_NO_ISOLATION")
#undef IMAGE_DLL_CHARACTERISTICS_NO_ISOLATION
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_NO_SEH")
#undef IMAGE_DLL_CHARACTERISTICS_NO_SEH
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_NX_COMPAT")
#undef IMAGE_DLL_CHARACTERISTICS_NX_COMPAT
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_TERMINAL_SERVER_AWARE")
#undef IMAGE_DLL_CHARACTERISTICS_TERMINAL_SERVER_AWARE
#pragma push_macro("IMAGE_DLL_CHARACTERISTICS_WDM_DRIVER")
#undef IMAGE_DLL_CHARACTERISTICS_WDM_DRIVER
#pragma push_macro("IMAGE_DVRT_ARM64X_FIXUP_TYPE_DELTA")
#undef IMAGE_DVRT_ARM64X_FIXUP_TYPE_DELTA
#pragma push_macro("IMAGE_DVRT_ARM64X_FIXUP_TYPE_VALUE")
#undef IMAGE_DVRT_ARM64X_FIXUP_TYPE_VALUE
#pragma push_macro("IMAGE_DVRT_ARM64X_FIXUP_TYPE_ZEROFILL")
#undef IMAGE_DVRT_ARM64X_FIXUP_TYPE_ZEROFILL
#pragma push_macro("IMAGE_DYNAMIC_RELOCATION_ARM64X")
#undef IMAGE_DYNAMIC_RELOCATION_ARM64X
#pragma push_macro("IMAGE_DYNAMIC_RELOCATION_GUARD_IMPORT_CONTROL_TRANSFER")
#undef IMAGE_DYNAMIC_RELOCATION_GUARD_IMPORT_CONTROL_TRANSFER
#pragma push_macro("IMAGE_DYNAMIC_RELOCATION_GUARD_INDIR_CONTROL_TRANSFER")
#undef IMAGE_DYNAMIC_RELOCATION_GUARD_INDIR_CONTROL_TRANSFER
#pragma push_macro("IMAGE_DYNAMIC_RELOCATION_GUARD_RF_EPILOGUE")
#undef IMAGE_DYNAMIC_RELOCATION_GUARD_RF_EPILOGUE
#pragma push_macro("IMAGE_DYNAMIC_RELOCATION_GUARD_RF_PROLOGUE")
#undef IMAGE_DYNAMIC_RELOCATION_GUARD_RF_PROLOGUE
#pragma push_macro("IMAGE_DYNAMIC_RELOCATION_GUARD_SWITCHTABLE_BRANCH")
#undef IMAGE_DYNAMIC_RELOCATION_GUARD_SWITCHTABLE_BRANCH
#pragma push_macro("IMAGE_FILE_32BIT_MACHINE")
#undef IMAGE_FILE_32BIT_MACHINE
#pragma push_macro("IMAGE_FILE_AGGRESSIVE_WS_TRIM")
#undef IMAGE_FILE_AGGRESSIVE_WS_TRIM
#pragma push_macro("IMAGE_FILE_BYTES_REVERSED_HI")
#undef IMAGE_FILE_BYTES_REVERSED_HI
#pragma push_macro("IMAGE_FILE_BYTES_REVERSED_LO")
#undef IMAGE_FILE_BYTES_REVERSED_LO
#pragma push_macro("IMAGE_FILE_DEBUG_STRIPPED")
#undef IMAGE_FILE_DEBUG_STRIPPED
#pragma push_macro("IMAGE_FILE_DLL")
#undef IMAGE_FILE_DLL
#pragma push_macro("IMAGE_FILE_EXECUTABLE_IMAGE")
#undef IMAGE_FILE_EXECUTABLE_IMAGE
#pragma push_macro("IMAGE_FILE_LARGE_ADDRESS_AWARE")
#undef IMAGE_FILE_LARGE_ADDRESS_AWARE
#pragma push_macro("IMAGE_FILE_LINE_NUMS_STRIPPED")
#undef IMAGE_FILE_LINE_NUMS_STRIPPED
#pragma push_macro("IMAGE_FILE_LOCAL_SYMS_STRIPPED")
#undef IMAGE_FILE_LOCAL_SYMS_STRIPPED
#pragma push_macro("IMAGE_FILE_MACHINE_AM33")
#undef IMAGE_FILE_MACHINE_AM33
#pragma push_macro("IMAGE_FILE_MACHINE_AMD64")
#undef IMAGE_FILE_MACHINE_AMD64
#pragma push_macro("IMAGE_FILE_MACHINE_ARM")
#undef IMAGE_FILE_MACHINE_ARM
#pragma push_macro("IMAGE_FILE_MACHINE_ARM64")
#undef IMAGE_FILE_MACHINE_ARM64
#pragma push_macro("IMAGE_FILE_MACHINE_ARM64EC")
#undef IMAGE_FILE_MACHINE_ARM64EC
#pragma push_macro("IMAGE_FILE_MACHINE_ARM64X")
#undef IMAGE_FILE_MACHINE_ARM64X
#pragma push_macro("IMAGE_FILE_MACHINE_ARMNT")
#undef IMAGE_FILE_MACHINE_ARMNT
#pragma push_macro("IMAGE_FILE_MACHINE_EBC")
#undef IMAGE_FILE_MACHINE_EBC
#pragma push_macro("IMAGE_FILE_MACHINE_I386")
#undef IMAGE_FILE_MACHINE_I386
#pragma push_macro("IMAGE_FILE_MACHINE_IA64")
#undef IMAGE_FILE_MACHINE_IA64
#pragma push_macro("IMAGE_FILE_MACHINE_M32R")
#undef IMAGE_FILE_MACHINE_M32R
#pragma push_macro("IMAGE_FILE_MACHINE_MIPS16")
#undef IMAGE_FILE_MACHINE_MIPS16
#pragma push_macro("IMAGE_FILE_MACHINE_MIPSFPU")
#undef IMAGE_FILE_MACHINE_MIPSFPU
#pragma push_macro("IMAGE_FILE_MACHINE_MIPSFPU16")
#undef IMAGE_FILE_MACHINE_MIPSFPU16
#pragma push_macro("IMAGE_FILE_MACHINE_POWERPC")
#undef IMAGE_FILE_MACHINE_POWERPC
#pragma push_macro("IMAGE_FILE_MACHINE_POWERPCFP")
#undef IMAGE_FILE_MACHINE_POWERPCFP
#pragma push_macro("IMAGE_FILE_MACHINE_R4000")
#undef IMAGE_FILE_MACHINE_R4000
#pragma push_macro("IMAGE_FILE_MACHINE_RISCV128")
#undef IMAGE_FILE_MACHINE_RISCV128
#pragma push_macro("IMAGE_FILE_MACHINE_RISCV32")
#undef IMAGE_FILE_MACHINE_RISCV32
#pragma push_macro("IMAGE_FILE_MACHINE_RISCV64")
#undef IMAGE_FILE_MACHINE_RISCV64
#pragma push_macro("IMAGE_FILE_MACHINE_SH3")
#undef IMAGE_FILE_MACHINE_SH3
#pragma push_macro("IMAGE_FILE_MACHINE_SH3DSP")
#undef IMAGE_FILE_MACHINE_SH3DSP
#pragma push_macro("IMAGE_FILE_MACHINE_SH4")
#undef IMAGE_FILE_MACHINE_SH4
#pragma push_macro("IMAGE_FILE_MACHINE_SH5")
#undef IMAGE_FILE_MACHINE_SH5
#pragma push_macro("IMAGE_FILE_MACHINE_THUMB")
#undef IMAGE_FILE_MACHINE_THUMB
#pragma push_macro("IMAGE_FILE_MACHINE_UNKNOWN")
#undef IMAGE_FILE_MACHINE_UNKNOWN
#pragma push_macro("IMAGE_FILE_MACHINE_WCEMIPSV2")
#undef IMAGE_FILE_MACHINE_WCEMIPSV2
#pragma push_macro("IMAGE_FILE_NET_RUN_FROM_SWAP")
#undef IMAGE_FILE_NET_RUN_FROM_SWAP
#pragma push_macro("IMAGE_FILE_RELOCS_STRIPPED")
#undef IMAGE_FILE_RELOCS_STRIPPED
#pragma push_macro("IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP")
#undef IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP
#pragma push_macro("IMAGE_FILE_SYSTEM")
#undef IMAGE_FILE_SYSTEM
#pragma push_macro("IMAGE_FILE_UP_SYSTEM_ONLY")
#undef IMAGE_FILE_UP_SYSTEM_ONLY
#pragma push_macro("IMAGE_LOAD_CONFIG_DIRECTORY32")
#undef IMAGE_LOAD_CONFIG_DIRECTORY32
#pragma push_macro("IMAGE_LOAD_CONFIG_DIRECTORY64")
#undef IMAGE_LOAD_CONFIG_DIRECTORY64
#pragma push_macro("IMAGE_REL_AMD64_ABSOLUTE")
#undef IMAGE_REL_AMD64_ABSOLUTE
#pragma push_macro("IMAGE_REL_AMD64_ADDR32")
#undef IMAGE_REL_AMD64_ADDR32
#pragma push_macro("IMAGE_REL_AMD64_ADDR32NB")
#undef IMAGE_REL_AMD64_ADDR32NB
#pragma push_macro("IMAGE_REL_AMD64_ADDR64")
#undef IMAGE_REL_AMD64_ADDR64
#pragma push_macro("IMAGE_REL_AMD64_PAIR")
#undef IMAGE_REL_AMD64_PAIR
#pragma push_macro("IMAGE_REL_AMD64_REL32")
#undef IMAGE_REL_AMD64_REL32
#pragma push_macro("IMAGE_REL_AMD64_REL32_1")
#undef IMAGE_REL_AMD64_REL32_1
#pragma push_macro("IMAGE_REL_AMD64_REL32_2")
#undef IMAGE_REL_AMD64_REL32_2
#pragma push_macro("IMAGE_REL_AMD64_REL32_3")
#undef IMAGE_REL_AMD64_REL32_3
#pragma push_macro("IMAGE_REL_AMD64_REL32_4")
#undef IMAGE_REL_AMD64_REL32_4
#pragma push_macro("IMAGE_REL_AMD64_REL32_5")
#undef IMAGE_REL_AMD64_REL32_5
#pragma push_macro("IMAGE_REL_AMD64_SECREL")
#undef IMAGE_REL_AMD64_SECREL
#pragma push_macro("IMAGE_REL_AMD64_SECREL7")
#undef IMAGE_REL_AMD64_SECREL7
#pragma push_macro("IMAGE_REL_AMD64_SECTION")
#undef IMAGE_REL_AMD64_SECTION
#pragma push_macro("IMAGE_REL_AMD64_SREL32")
#undef IMAGE_REL_AMD64_SREL32
#pragma push_macro("IMAGE_REL_AMD64_SSPAN32")
#undef IMAGE_REL_AMD64_SSPAN32
#pragma push_macro("IMAGE_REL_AMD64_TOKEN")
#undef IMAGE_REL_AMD64_TOKEN
#pragma push_macro("IMAGE_REL_ARM64_ABSOLUTE")
#undef IMAGE_REL_ARM64_ABSOLUTE
#pragma push_macro("IMAGE_REL_ARM64_ADDR32")
#undef IMAGE_REL_ARM64_ADDR32
#pragma push_macro("IMAGE_REL_ARM64_ADDR32NB")
#undef IMAGE_REL_ARM64_ADDR32NB
#pragma push_macro("IMAGE_REL_ARM64_ADDR64")
#undef IMAGE_REL_ARM64_ADDR64
#pragma push_macro("IMAGE_REL_ARM64_BRANCH14")
#undef IMAGE_REL_ARM64_BRANCH14
#pragma push_macro("IMAGE_REL_ARM64_BRANCH19")
#undef IMAGE_REL_ARM64_BRANCH19
#pragma push_macro("IMAGE_REL_ARM64_BRANCH26")
#undef IMAGE_REL_ARM64_BRANCH26
#pragma push_macro("IMAGE_REL_ARM64_PAGEBASE_REL21")
#undef IMAGE_REL_ARM64_PAGEBASE_REL21
#pragma push_macro("IMAGE_REL_ARM64_PAGEOFFSET_12A")
#undef IMAGE_REL_ARM64_PAGEOFFSET_12A
#pragma push_macro("IMAGE_REL_ARM64_PAGEOFFSET_12L")
#undef IMAGE_REL_ARM64_PAGEOFFSET_12L
#pragma push_macro("IMAGE_REL_ARM64_REL21")
#undef IMAGE_REL_ARM64_REL21
#pragma push_macro("IMAGE_REL_ARM64_REL32")
#undef IMAGE_REL_ARM64_REL32
#pragma push_macro("IMAGE_REL_ARM64_SECREL")
#undef IMAGE_REL_ARM64_SECREL
#pragma push_macro("IMAGE_REL_ARM64_SECREL_HIGH12A")
#undef IMAGE_REL_ARM64_SECREL_HIGH12A
#pragma push_macro("IMAGE_REL_ARM64_SECREL_LOW12A")
#undef IMAGE_REL_ARM64_SECREL_LOW12A
#pragma push_macro("IMAGE_REL_ARM64_SECREL_LOW12L")
#undef IMAGE_REL_ARM64_SECREL_LOW12L
#pragma push_macro("IMAGE_REL_ARM64_SECTION")
#undef IMAGE_REL_ARM64_SECTION
#pragma push_macro("IMAGE_REL_ARM64_TOKEN")
#undef IMAGE_REL_ARM64_TOKEN
#pragma push_macro("IMAGE_REL_ARM_ABSOLUTE")
#undef IMAGE_REL_ARM_ABSOLUTE
#pragma push_macro("IMAGE_REL_ARM_ADDR32")
#undef IMAGE_REL_ARM_ADDR32
#pragma push_macro("IMAGE_REL_ARM_ADDR32NB")
#undef IMAGE_REL_ARM_ADDR32NB
#pragma push_macro("IMAGE_REL_ARM_BLX11")
#undef IMAGE_REL_ARM_BLX11
#pragma push_macro("IMAGE_REL_ARM_BLX23T")
#undef IMAGE_REL_ARM_BLX23T
#pragma push_macro("IMAGE_REL_ARM_BLX24")
#undef IMAGE_REL_ARM_BLX24
#pragma push_macro("IMAGE_REL_ARM_BRANCH11")
#undef IMAGE_REL_ARM_BRANCH11
#pragma push_macro("IMAGE_REL_ARM_BRANCH20T")
#undef IMAGE_REL_ARM_BRANCH20T
#pragma push_macro("IMAGE_REL_ARM_BRANCH24")
#undef IMAGE_REL_ARM_BRANCH24
#pragma push_macro("IMAGE_REL_ARM_BRANCH24T")
#undef IMAGE_REL_ARM_BRANCH24T
#pragma push_macro("IMAGE_REL_ARM_MOV32A")
#undef IMAGE_REL_ARM_MOV32A
#pragma push_macro("IMAGE_REL_ARM_MOV32T")
#undef IMAGE_REL_ARM_MOV32T
#pragma push_macro("IMAGE_REL_ARM_PAIR")
#undef IMAGE_REL_ARM_PAIR
#pragma push_macro("IMAGE_REL_ARM_REL32")
#undef IMAGE_REL_ARM_REL32
#pragma push_macro("IMAGE_REL_ARM_SECREL")
#undef IMAGE_REL_ARM_SECREL
#pragma push_macro("IMAGE_REL_ARM_SECTION")
#undef IMAGE_REL_ARM_SECTION
#pragma push_macro("IMAGE_REL_ARM_TOKEN")
#undef IMAGE_REL_ARM_TOKEN
#pragma push_macro("IMAGE_REL_BASED_ABSOLUTE")
#undef IMAGE_REL_BASED_ABSOLUTE
#pragma push_macro("IMAGE_REL_BASED_ARM_MOV32A")
#undef IMAGE_REL_BASED_ARM_MOV32A
#pragma push_macro("IMAGE_REL_BASED_ARM_MOV32T")
#undef IMAGE_REL_BASED_ARM_MOV32T
#pragma push_macro("IMAGE_REL_BASED_DIR64")
#undef IMAGE_REL_BASED_DIR64
#pragma push_macro("IMAGE_REL_BASED_HIGH")
#undef IMAGE_REL_BASED_HIGH
#pragma push_macro("IMAGE_REL_BASED_HIGHADJ")
#undef IMAGE_REL_BASED_HIGHADJ
#pragma push_macro("IMAGE_REL_BASED_HIGHLOW")
#undef IMAGE_REL_BASED_HIGHLOW
#pragma push_macro("IMAGE_REL_BASED_LOW")
#undef IMAGE_REL_BASED_LOW
#pragma push_macro("IMAGE_REL_BASED_MIPS_JMPADDR")
#undef IMAGE_REL_BASED_MIPS_JMPADDR
#pragma push_macro("IMAGE_REL_BASED_MIPS_JMPADDR16")
#undef IMAGE_REL_BASED_MIPS_JMPADDR16
#pragma push_macro("IMAGE_REL_I386_ABSOLUTE")
#undef IMAGE_REL_I386_ABSOLUTE
#pragma push_macro("IMAGE_REL_I386_DIR16")
#undef IMAGE_REL_I386_DIR16
#pragma push_macro("IMAGE_REL_I386_DIR32")
#undef IMAGE_REL_I386_DIR32
#pragma push_macro("IMAGE_REL_I386_DIR32NB")
#undef IMAGE_REL_I386_DIR32NB
#pragma push_macro("IMAGE_REL_I386_REL16")
#undef IMAGE_REL_I386_REL16
#pragma push_macro("IMAGE_REL_I386_REL32")
#undef IMAGE_REL_I386_REL32
#pragma push_macro("IMAGE_REL_I386_SECREL")
#undef IMAGE_REL_I386_SECREL
#pragma push_macro("IMAGE_REL_I386_SECREL7")
#undef IMAGE_REL_I386_SECREL7
#pragma push_macro("IMAGE_REL_I386_SECTION")
#undef IMAGE_REL_I386_SECTION
#pragma push_macro("IMAGE_REL_I386_SEG12")
#undef IMAGE_REL_I386_SEG12
#pragma push_macro("IMAGE_REL_I386_TOKEN")
#undef IMAGE_REL_I386_TOKEN
#pragma push_macro("IMAGE_REL_MIPS_ABSOLUTE")
#undef IMAGE_REL_MIPS_ABSOLUTE
#pragma push_macro("IMAGE_REL_MIPS_GPREL")
#undef IMAGE_REL_MIPS_GPREL
#pragma push_macro("IMAGE_REL_MIPS_JMPADDR")
#undef IMAGE_REL_MIPS_JMPADDR
#pragma push_macro("IMAGE_REL_MIPS_JMPADDR16")
#undef IMAGE_REL_MIPS_JMPADDR16
#pragma push_macro("IMAGE_REL_MIPS_LITERAL")
#undef IMAGE_REL_MIPS_LITERAL
#pragma push_macro("IMAGE_REL_MIPS_PAIR")
#undef IMAGE_REL_MIPS_PAIR
#pragma push_macro("IMAGE_REL_MIPS_REFHALF")
#undef IMAGE_REL_MIPS_REFHALF
#pragma push_macro("IMAGE_REL_MIPS_REFHI")
#undef IMAGE_REL_MIPS_REFHI
#pragma push_macro("IMAGE_REL_MIPS_REFLO")
#undef IMAGE_REL_MIPS_REFLO
#pragma push_macro("IMAGE_REL_MIPS_REFWORD")
#undef IMAGE_REL_MIPS_REFWORD
#pragma push_macro("IMAGE_REL_MIPS_REFWORDNB")
#undef IMAGE_REL_MIPS_REFWORDNB
#pragma push_macro("IMAGE_REL_MIPS_SECREL")
#undef IMAGE_REL_MIPS_SECREL
#pragma push_macro("IMAGE_REL_MIPS_SECRELHI")
#undef IMAGE_REL_MIPS_SECRELHI
#pragma push_macro("IMAGE_REL_MIPS_SECRELLO")
#undef IMAGE_REL_MIPS_SECRELLO
#pragma push_macro("IMAGE_REL_MIPS_SECTION")
#undef IMAGE_REL_MIPS_SECTION
#pragma push_macro("IMAGE_SCN_ALIGN_1024BYTES")
#undef IMAGE_SCN_ALIGN_1024BYTES
#pragma push_macro("IMAGE_SCN_ALIGN_128BYTES")
#undef IMAGE_SCN_ALIGN_128BYTES
#pragma push_macro("IMAGE_SCN_ALIGN_16BYTES")
#undef IMAGE_SCN_ALIGN_16BYTES
#pragma push_macro("IMAGE_SCN_ALIGN_1BYTES")
#undef IMAGE_SCN_ALIGN_1BYTES
#pragma push_macro("IMAGE_SCN_ALIGN_2048BYTES")
#undef IMAGE_SCN_ALIGN_2048BYTES
#pragma push_macro("IMAGE_SCN_ALIGN_256BYTES")
#undef IMAGE_SCN_ALIGN_256BYTES
#pragma push_macro("IMAGE_SCN_ALIGN_2BYTES")
#undef IMAGE_SCN_ALIGN_2BYTES
#pragma push_macro("IMAGE_SCN_ALIGN_32BYTES")
#undef IMAGE_SCN_ALIGN_32BYTES
#pragma push_macro("IMAGE_SCN_ALIGN_4096BYTES")
#undef IMAGE_SCN_ALIGN_4096BYTES
#pragma push_macro("IMAGE_SCN_ALIGN_4BYTES")
#undef IMAGE_SCN_ALIGN_4BYTES
#pragma push_macro("IMAGE_SCN_ALIGN_512BYTES")
#undef IMAGE_SCN_ALIGN_512BYTES
#pragma push_macro("IMAGE_SCN_ALIGN_64BYTES")
#undef IMAGE_SCN_ALIGN_64BYTES
#pragma push_macro("IMAGE_SCN_ALIGN_8192BYTES")
#undef IMAGE_SCN_ALIGN_8192BYTES
#pragma push_macro("IMAGE_SCN_ALIGN_8BYTES")
#undef IMAGE_SCN_ALIGN_8BYTES
#pragma push_macro("IMAGE_SCN_ALIGN_MASK")
#undef IMAGE_SCN_ALIGN_MASK
#pragma push_macro("IMAGE_SCN_CNT_CODE")
#undef IMAGE_SCN_CNT_CODE
#pragma push_macro("IMAGE_SCN_CNT_INITIALIZED_DATA")
#undef IMAGE_SCN_CNT_INITIALIZED_DATA
#pragma push_macro("IMAGE_SCN_CNT_UNINITIALIZED_DATA")
#undef IMAGE_SCN_CNT_UNINITIALIZED_DATA
#pragma push_macro("IMAGE_SCN_GPREL")
#undef IMAGE_SCN_GPREL
#pragma push_macro("IMAGE_SCN_LNK_COMDAT")
#undef IMAGE_SCN_LNK_COMDAT
#pragma push_macro("IMAGE_SCN_LNK_INFO")
#undef IMAGE_SCN_LNK_INFO
#pragma push_macro("IMAGE_SCN_LNK_NRELOC_OVFL")
#undef IMAGE_SCN_LNK_NRELOC_OVFL
#pragma push_macro("IMAGE_SCN_LNK_OTHER")
#undef IMAGE_SCN_LNK_OTHER
#pragma push_macro("IMAGE_SCN_LNK_REMOVE")
#undef IMAGE_SCN_LNK_REMOVE
#pragma push_macro("IMAGE_SCN_MEM_16BIT")
#undef IMAGE_SCN_MEM_16BIT
#pragma push_macro("IMAGE_SCN_MEM_DISCARDABLE")
#undef IMAGE_SCN_MEM_DISCARDABLE
#pragma push_macro("IMAGE_SCN_MEM_EXECUTE")
#undef IMAGE_SCN_MEM_EXECUTE
#pragma push_macro("IMAGE_SCN_MEM_LOCKED")
#undef IMAGE_SCN_MEM_LOCKED
#pragma push_macro("IMAGE_SCN_MEM_NOT_CACHED")
#undef IMAGE_SCN_MEM_NOT_CACHED
#pragma push_macro("IMAGE_SCN_MEM_NOT_PAGED")
#undef IMAGE_SCN_MEM_NOT_PAGED
#pragma push_macro("IMAGE_SCN_MEM_PRELOAD")
#undef IMAGE_SCN_MEM_PRELOAD
#pragma push_macro("IMAGE_SCN_MEM_PURGEABLE")
#undef IMAGE_SCN_MEM_PURGEABLE
#pragma push_macro("IMAGE_SCN_MEM_READ")
#undef IMAGE_SCN_MEM_READ
#pragma push_macro("IMAGE_SCN_MEM_SHARED")
#undef IMAGE_SCN_MEM_SHARED
#pragma push_macro("IMAGE_SCN_MEM_WRITE")
#undef IMAGE_SCN_MEM_WRITE
#pragma push_macro("IMAGE_SCN_TYPE_NOLOAD")
#undef IMAGE_SCN_TYPE_NOLOAD
#pragma push_macro("IMAGE_SCN_TYPE_NO_PAD")
#undef IMAGE_SCN_TYPE_NO_PAD
#pragma push_macro("IMAGE_SUBSYSTEM_EFI_APPLICATION")
#undef IMAGE_SUBSYSTEM_EFI_APPLICATION
#pragma push_macro("IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER")
#undef IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER
#pragma push_macro("IMAGE_SUBSYSTEM_EFI_ROM")
#undef IMAGE_SUBSYSTEM_EFI_ROM
#pragma push_macro("IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER")
#undef IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER
#pragma push_macro("IMAGE_SUBSYSTEM_NATIVE")
#undef IMAGE_SUBSYSTEM_NATIVE
#pragma push_macro("IMAGE_SUBSYSTEM_NATIVE_WINDOWS")
#undef IMAGE_SUBSYSTEM_NATIVE_WINDOWS
#pragma push_macro("IMAGE_SUBSYSTEM_OS2_CUI")
#undef IMAGE_SUBSYSTEM_OS2_CUI
#pragma push_macro("IMAGE_SUBSYSTEM_POSIX_CUI")
#undef IMAGE_SUBSYSTEM_POSIX_CUI
#pragma push_macro("IMAGE_SUBSYSTEM_UNKNOWN")
#undef IMAGE_SUBSYSTEM_UNKNOWN
#pragma push_macro("IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION")
#undef IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION
#pragma push_macro("IMAGE_SUBSYSTEM_WINDOWS_CE_GUI")
#undef IMAGE_SUBSYSTEM_WINDOWS_CE_GUI
#pragma push_macro("IMAGE_SUBSYSTEM_WINDOWS_CUI")
#undef IMAGE_SUBSYSTEM_WINDOWS_CUI
#pragma push_macro("IMAGE_SUBSYSTEM_WINDOWS_GUI")
#undef IMAGE_SUBSYSTEM_WINDOWS_GUI
#pragma push_macro("IMAGE_SUBSYSTEM_XBOX")
#undef IMAGE_SUBSYSTEM_XBOX
#pragma push_macro("IMAGE_SYM_ABSOLUTE")
#undef IMAGE_SYM_ABSOLUTE
#pragma push_macro("IMAGE_SYM_CLASS_ARGUMENT")
#undef IMAGE_SYM_CLASS_ARGUMENT
#pragma push_macro("IMAGE_SYM_CLASS_AUTOMATIC")
#undef IMAGE_SYM_CLASS_AUTOMATIC
#pragma push_macro("IMAGE_SYM_CLASS_BIT_FIELD")
#undef IMAGE_SYM_CLASS_BIT_FIELD
#pragma push_macro("IMAGE_SYM_CLASS_BLOCK")
#undef IMAGE_SYM_CLASS_BLOCK
#pragma push_macro("IMAGE_SYM_CLASS_CLR_TOKEN")
#undef IMAGE_SYM_CLASS_CLR_TOKEN
#pragma push_macro("IMAGE_SYM_CLASS_END_OF_FUNCTION")
#undef IMAGE_SYM_CLASS_END_OF_FUNCTION
#pragma push_macro("IMAGE_SYM_CLASS_END_OF_STRUCT")
#undef IMAGE_SYM_CLASS_END_OF_STRUCT
#pragma push_macro("IMAGE_SYM_CLASS_ENUM_TAG")
#undef IMAGE_SYM_CLASS_ENUM_TAG
#pragma push_macro("IMAGE_SYM_CLASS_EXTERNAL")
#undef IMAGE_SYM_CLASS_EXTERNAL
#pragma push_macro("IMAGE_SYM_CLASS_EXTERNAL_DEF")
#undef IMAGE_SYM_CLASS_EXTERNAL_DEF
#pragma push_macro("IMAGE_SYM_CLASS_FILE")
#undef IMAGE_SYM_CLASS_FILE
#pragma push_macro("IMAGE_SYM_CLASS_FUNCTION")
#undef IMAGE_SYM_CLASS_FUNCTION
#pragma push_macro("IMAGE_SYM_CLASS_LABEL")
#undef IMAGE_SYM_CLASS_LABEL
#pragma push_macro("IMAGE_SYM_CLASS_MEMBER_OF_ENUM")
#undef IMAGE_SYM_CLASS_MEMBER_OF_ENUM
#pragma push_macro("IMAGE_SYM_CLASS_MEMBER_OF_STRUCT")
#undef IMAGE_SYM_CLASS_MEMBER_OF_STRUCT
#pragma push_macro("IMAGE_SYM_CLASS_MEMBER_OF_UNION")
#undef IMAGE_SYM_CLASS_MEMBER_OF_UNION
#pragma push_macro("IMAGE_SYM_CLASS_NULL")
#undef IMAGE_SYM_CLASS_NULL
#pragma push_macro("IMAGE_SYM_CLASS_REGISTER")
#undef IMAGE_SYM_CLASS_REGISTER
#pragma push_macro("IMAGE_SYM_CLASS_REGISTER_PARAM")
#undef IMAGE_SYM_CLASS_REGISTER_PARAM
#pragma push_macro("IMAGE_SYM_CLASS_SECTION")
#undef IMAGE_SYM_CLASS_SECTION
#pragma push_macro("IMAGE_SYM_CLASS_STATIC")
#undef IMAGE_SYM_CLASS_STATIC
#pragma push_macro("IMAGE_SYM_CLASS_STRUCT_TAG")
#undef IMAGE_SYM_CLASS_STRUCT_TAG
#pragma push_macro("IMAGE_SYM_CLASS_TYPE_DEFINITION")
#undef IMAGE_SYM_CLASS_TYPE_DEFINITION
#pragma push_macro("IMAGE_SYM_CLASS_UNDEFINED_LABEL")
#undef IMAGE_SYM_CLASS_UNDEFINED_LABEL
#pragma push_macro("IMAGE_SYM_CLASS_UNDEFINED_STATIC")
#undef IMAGE_SYM_CLASS_UNDEFINED_STATIC
#pragma push_macro("IMAGE_SYM_CLASS_UNION_TAG")
#undef IMAGE_SYM_CLASS_UNION_TAG
#pragma push_macro("IMAGE_SYM_CLASS_WEAK_EXTERNAL")
#undef IMAGE_SYM_CLASS_WEAK_EXTERNAL
#pragma push_macro("IMAGE_SYM_DEBUG")
#undef IMAGE_SYM_DEBUG
#pragma push_macro("IMAGE_SYM_DTYPE_ARRAY")
#undef IMAGE_SYM_DTYPE_ARRAY
#pragma push_macro("IMAGE_SYM_DTYPE_FUNCTION")
#undef IMAGE_SYM_DTYPE_FUNCTION
#pragma push_macro("IMAGE_SYM_DTYPE_NULL")
#undef IMAGE_SYM_DTYPE_NULL
#pragma push_macro("IMAGE_SYM_DTYPE_POINTER")
#undef IMAGE_SYM_DTYPE_POINTER
#pragma push_macro("IMAGE_SYM_TYPE_BYTE")
#undef IMAGE_SYM_TYPE_BYTE
#pragma push_macro("IMAGE_SYM_TYPE_CHAR")
#undef IMAGE_SYM_TYPE_CHAR
#pragma push_macro("IMAGE_SYM_TYPE_DOUBLE")
#undef IMAGE_SYM_TYPE_DOUBLE
#pragma push_macro("IMAGE_SYM_TYPE_DWORD")
#undef IMAGE_SYM_TYPE_DWORD
#pragma push_macro("IMAGE_SYM_TYPE_ENUM")
#undef IMAGE_SYM_TYPE_ENUM
#pragma push_macro("IMAGE_SYM_TYPE_FLOAT")
#undef IMAGE_SYM_TYPE_FLOAT
#pragma push_macro("IMAGE_SYM_TYPE_INT")
#undef IMAGE_SYM_TYPE_INT
#pragma push_macro("IMAGE_SYM_TYPE_LONG")
#undef IMAGE_SYM_TYPE_LONG
#pragma push_macro("IMAGE_SYM_TYPE_MOE")
#undef IMAGE_SYM_TYPE_MOE
#pragma push_macro("IMAGE_SYM_TYPE_NULL")
#undef IMAGE_SYM_TYPE_NULL
#pragma push_macro("IMAGE_SYM_TYPE_SHORT")
#undef IMAGE_SYM_TYPE_SHORT
#pragma push_macro("IMAGE_SYM_TYPE_STRUCT")
#undef IMAGE_SYM_TYPE_STRUCT
#pragma push_macro("IMAGE_SYM_TYPE_UINT")
#undef IMAGE_SYM_TYPE_UINT
#pragma push_macro("IMAGE_SYM_TYPE_UNION")
#undef IMAGE_SYM_TYPE_UNION
#pragma push_macro("IMAGE_SYM_TYPE_VOID")
#undef IMAGE_SYM_TYPE_VOID
#pragma push_macro("IMAGE_SYM_TYPE_WORD")
#undef IMAGE_SYM_TYPE_WORD
#pragma push_macro("IMAGE_SYM_UNDEFINED")
#undef IMAGE_SYM_UNDEFINED
#pragma push_macro("IMAGE_WEAK_EXTERN_ANTI_DEPENDENCY")
#undef IMAGE_WEAK_EXTERN_ANTI_DEPENDENCY
#pragma push_macro("IMAGE_WEAK_EXTERN_SEARCH_ALIAS")
#undef IMAGE_WEAK_EXTERN_SEARCH_ALIAS
#pragma push_macro("IMAGE_WEAK_EXTERN_SEARCH_LIBRARY")
#undef IMAGE_WEAK_EXTERN_SEARCH_LIBRARY
#pragma push_macro("IMAGE_WEAK_EXTERN_SEARCH_NOLIBRARY")
#undef IMAGE_WEAK_EXTERN_SEARCH_NOLIBRARY

#include <llvm/BinaryFormat/COFF.h>
#include <llvm/Object/COFF.h>

namespace uwvm2::runtime::compiler::llvm_jit::win64_coff_constants
{
    // Copy the actual LLVM wire constants while their spellings are shielded.
    // These values carry no pointer, image ownership or registration authority;
    // the section manager's original object/section/relocation checks remain.
    // Consumers use these non-macro names AFTER the SDK macros are restored.
    inline constexpr auto machine_amd64{::llvm::COFF::IMAGE_FILE_MACHINE_AMD64};
    inline constexpr auto machine_arm64{::llvm::COFF::IMAGE_FILE_MACHINE_ARM64};
    inline constexpr auto relocation_amd64_addr32nb{::llvm::COFF::IMAGE_REL_AMD64_ADDR32NB};
    inline constexpr auto relocation_arm64_addr32nb{::llvm::COFF::IMAGE_REL_ARM64_ADDR32NB};
    inline constexpr auto relocation_i386_dir32{::llvm::COFF::IMAGE_REL_I386_DIR32};
    inline constexpr auto relocation_amd64_addr64{::llvm::COFF::IMAGE_REL_AMD64_ADDR64};
    inline constexpr auto relocation_arm64_addr64{::llvm::COFF::IMAGE_REL_ARM64_ADDR64};
    inline constexpr auto relocation_arm_addr32{::llvm::COFF::IMAGE_REL_ARM_ADDR32};
}

#pragma pop_macro("IMAGE_WEAK_EXTERN_SEARCH_NOLIBRARY")
#pragma pop_macro("IMAGE_WEAK_EXTERN_SEARCH_LIBRARY")
#pragma pop_macro("IMAGE_WEAK_EXTERN_SEARCH_ALIAS")
#pragma pop_macro("IMAGE_WEAK_EXTERN_ANTI_DEPENDENCY")
#pragma pop_macro("IMAGE_SYM_UNDEFINED")
#pragma pop_macro("IMAGE_SYM_TYPE_WORD")
#pragma pop_macro("IMAGE_SYM_TYPE_VOID")
#pragma pop_macro("IMAGE_SYM_TYPE_UNION")
#pragma pop_macro("IMAGE_SYM_TYPE_UINT")
#pragma pop_macro("IMAGE_SYM_TYPE_STRUCT")
#pragma pop_macro("IMAGE_SYM_TYPE_SHORT")
#pragma pop_macro("IMAGE_SYM_TYPE_NULL")
#pragma pop_macro("IMAGE_SYM_TYPE_MOE")
#pragma pop_macro("IMAGE_SYM_TYPE_LONG")
#pragma pop_macro("IMAGE_SYM_TYPE_INT")
#pragma pop_macro("IMAGE_SYM_TYPE_FLOAT")
#pragma pop_macro("IMAGE_SYM_TYPE_ENUM")
#pragma pop_macro("IMAGE_SYM_TYPE_DWORD")
#pragma pop_macro("IMAGE_SYM_TYPE_DOUBLE")
#pragma pop_macro("IMAGE_SYM_TYPE_CHAR")
#pragma pop_macro("IMAGE_SYM_TYPE_BYTE")
#pragma pop_macro("IMAGE_SYM_DTYPE_POINTER")
#pragma pop_macro("IMAGE_SYM_DTYPE_NULL")
#pragma pop_macro("IMAGE_SYM_DTYPE_FUNCTION")
#pragma pop_macro("IMAGE_SYM_DTYPE_ARRAY")
#pragma pop_macro("IMAGE_SYM_DEBUG")
#pragma pop_macro("IMAGE_SYM_CLASS_WEAK_EXTERNAL")
#pragma pop_macro("IMAGE_SYM_CLASS_UNION_TAG")
#pragma pop_macro("IMAGE_SYM_CLASS_UNDEFINED_STATIC")
#pragma pop_macro("IMAGE_SYM_CLASS_UNDEFINED_LABEL")
#pragma pop_macro("IMAGE_SYM_CLASS_TYPE_DEFINITION")
#pragma pop_macro("IMAGE_SYM_CLASS_STRUCT_TAG")
#pragma pop_macro("IMAGE_SYM_CLASS_STATIC")
#pragma pop_macro("IMAGE_SYM_CLASS_SECTION")
#pragma pop_macro("IMAGE_SYM_CLASS_REGISTER_PARAM")
#pragma pop_macro("IMAGE_SYM_CLASS_REGISTER")
#pragma pop_macro("IMAGE_SYM_CLASS_NULL")
#pragma pop_macro("IMAGE_SYM_CLASS_MEMBER_OF_UNION")
#pragma pop_macro("IMAGE_SYM_CLASS_MEMBER_OF_STRUCT")
#pragma pop_macro("IMAGE_SYM_CLASS_MEMBER_OF_ENUM")
#pragma pop_macro("IMAGE_SYM_CLASS_LABEL")
#pragma pop_macro("IMAGE_SYM_CLASS_FUNCTION")
#pragma pop_macro("IMAGE_SYM_CLASS_FILE")
#pragma pop_macro("IMAGE_SYM_CLASS_EXTERNAL_DEF")
#pragma pop_macro("IMAGE_SYM_CLASS_EXTERNAL")
#pragma pop_macro("IMAGE_SYM_CLASS_ENUM_TAG")
#pragma pop_macro("IMAGE_SYM_CLASS_END_OF_STRUCT")
#pragma pop_macro("IMAGE_SYM_CLASS_END_OF_FUNCTION")
#pragma pop_macro("IMAGE_SYM_CLASS_CLR_TOKEN")
#pragma pop_macro("IMAGE_SYM_CLASS_BLOCK")
#pragma pop_macro("IMAGE_SYM_CLASS_BIT_FIELD")
#pragma pop_macro("IMAGE_SYM_CLASS_AUTOMATIC")
#pragma pop_macro("IMAGE_SYM_CLASS_ARGUMENT")
#pragma pop_macro("IMAGE_SYM_ABSOLUTE")
#pragma pop_macro("IMAGE_SUBSYSTEM_XBOX")
#pragma pop_macro("IMAGE_SUBSYSTEM_WINDOWS_GUI")
#pragma pop_macro("IMAGE_SUBSYSTEM_WINDOWS_CUI")
#pragma pop_macro("IMAGE_SUBSYSTEM_WINDOWS_CE_GUI")
#pragma pop_macro("IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION")
#pragma pop_macro("IMAGE_SUBSYSTEM_UNKNOWN")
#pragma pop_macro("IMAGE_SUBSYSTEM_POSIX_CUI")
#pragma pop_macro("IMAGE_SUBSYSTEM_OS2_CUI")
#pragma pop_macro("IMAGE_SUBSYSTEM_NATIVE_WINDOWS")
#pragma pop_macro("IMAGE_SUBSYSTEM_NATIVE")
#pragma pop_macro("IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER")
#pragma pop_macro("IMAGE_SUBSYSTEM_EFI_ROM")
#pragma pop_macro("IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER")
#pragma pop_macro("IMAGE_SUBSYSTEM_EFI_APPLICATION")
#pragma pop_macro("IMAGE_SCN_TYPE_NO_PAD")
#pragma pop_macro("IMAGE_SCN_TYPE_NOLOAD")
#pragma pop_macro("IMAGE_SCN_MEM_WRITE")
#pragma pop_macro("IMAGE_SCN_MEM_SHARED")
#pragma pop_macro("IMAGE_SCN_MEM_READ")
#pragma pop_macro("IMAGE_SCN_MEM_PURGEABLE")
#pragma pop_macro("IMAGE_SCN_MEM_PRELOAD")
#pragma pop_macro("IMAGE_SCN_MEM_NOT_PAGED")
#pragma pop_macro("IMAGE_SCN_MEM_NOT_CACHED")
#pragma pop_macro("IMAGE_SCN_MEM_LOCKED")
#pragma pop_macro("IMAGE_SCN_MEM_EXECUTE")
#pragma pop_macro("IMAGE_SCN_MEM_DISCARDABLE")
#pragma pop_macro("IMAGE_SCN_MEM_16BIT")
#pragma pop_macro("IMAGE_SCN_LNK_REMOVE")
#pragma pop_macro("IMAGE_SCN_LNK_OTHER")
#pragma pop_macro("IMAGE_SCN_LNK_NRELOC_OVFL")
#pragma pop_macro("IMAGE_SCN_LNK_INFO")
#pragma pop_macro("IMAGE_SCN_LNK_COMDAT")
#pragma pop_macro("IMAGE_SCN_GPREL")
#pragma pop_macro("IMAGE_SCN_CNT_UNINITIALIZED_DATA")
#pragma pop_macro("IMAGE_SCN_CNT_INITIALIZED_DATA")
#pragma pop_macro("IMAGE_SCN_CNT_CODE")
#pragma pop_macro("IMAGE_SCN_ALIGN_MASK")
#pragma pop_macro("IMAGE_SCN_ALIGN_8BYTES")
#pragma pop_macro("IMAGE_SCN_ALIGN_8192BYTES")
#pragma pop_macro("IMAGE_SCN_ALIGN_64BYTES")
#pragma pop_macro("IMAGE_SCN_ALIGN_512BYTES")
#pragma pop_macro("IMAGE_SCN_ALIGN_4BYTES")
#pragma pop_macro("IMAGE_SCN_ALIGN_4096BYTES")
#pragma pop_macro("IMAGE_SCN_ALIGN_32BYTES")
#pragma pop_macro("IMAGE_SCN_ALIGN_2BYTES")
#pragma pop_macro("IMAGE_SCN_ALIGN_256BYTES")
#pragma pop_macro("IMAGE_SCN_ALIGN_2048BYTES")
#pragma pop_macro("IMAGE_SCN_ALIGN_1BYTES")
#pragma pop_macro("IMAGE_SCN_ALIGN_16BYTES")
#pragma pop_macro("IMAGE_SCN_ALIGN_128BYTES")
#pragma pop_macro("IMAGE_SCN_ALIGN_1024BYTES")
#pragma pop_macro("IMAGE_REL_MIPS_SECTION")
#pragma pop_macro("IMAGE_REL_MIPS_SECRELLO")
#pragma pop_macro("IMAGE_REL_MIPS_SECRELHI")
#pragma pop_macro("IMAGE_REL_MIPS_SECREL")
#pragma pop_macro("IMAGE_REL_MIPS_REFWORDNB")
#pragma pop_macro("IMAGE_REL_MIPS_REFWORD")
#pragma pop_macro("IMAGE_REL_MIPS_REFLO")
#pragma pop_macro("IMAGE_REL_MIPS_REFHI")
#pragma pop_macro("IMAGE_REL_MIPS_REFHALF")
#pragma pop_macro("IMAGE_REL_MIPS_PAIR")
#pragma pop_macro("IMAGE_REL_MIPS_LITERAL")
#pragma pop_macro("IMAGE_REL_MIPS_JMPADDR16")
#pragma pop_macro("IMAGE_REL_MIPS_JMPADDR")
#pragma pop_macro("IMAGE_REL_MIPS_GPREL")
#pragma pop_macro("IMAGE_REL_MIPS_ABSOLUTE")
#pragma pop_macro("IMAGE_REL_I386_TOKEN")
#pragma pop_macro("IMAGE_REL_I386_SEG12")
#pragma pop_macro("IMAGE_REL_I386_SECTION")
#pragma pop_macro("IMAGE_REL_I386_SECREL7")
#pragma pop_macro("IMAGE_REL_I386_SECREL")
#pragma pop_macro("IMAGE_REL_I386_REL32")
#pragma pop_macro("IMAGE_REL_I386_REL16")
#pragma pop_macro("IMAGE_REL_I386_DIR32NB")
#pragma pop_macro("IMAGE_REL_I386_DIR32")
#pragma pop_macro("IMAGE_REL_I386_DIR16")
#pragma pop_macro("IMAGE_REL_I386_ABSOLUTE")
#pragma pop_macro("IMAGE_REL_BASED_MIPS_JMPADDR16")
#pragma pop_macro("IMAGE_REL_BASED_MIPS_JMPADDR")
#pragma pop_macro("IMAGE_REL_BASED_LOW")
#pragma pop_macro("IMAGE_REL_BASED_HIGHLOW")
#pragma pop_macro("IMAGE_REL_BASED_HIGHADJ")
#pragma pop_macro("IMAGE_REL_BASED_HIGH")
#pragma pop_macro("IMAGE_REL_BASED_DIR64")
#pragma pop_macro("IMAGE_REL_BASED_ARM_MOV32T")
#pragma pop_macro("IMAGE_REL_BASED_ARM_MOV32A")
#pragma pop_macro("IMAGE_REL_BASED_ABSOLUTE")
#pragma pop_macro("IMAGE_REL_ARM_TOKEN")
#pragma pop_macro("IMAGE_REL_ARM_SECTION")
#pragma pop_macro("IMAGE_REL_ARM_SECREL")
#pragma pop_macro("IMAGE_REL_ARM_REL32")
#pragma pop_macro("IMAGE_REL_ARM_PAIR")
#pragma pop_macro("IMAGE_REL_ARM_MOV32T")
#pragma pop_macro("IMAGE_REL_ARM_MOV32A")
#pragma pop_macro("IMAGE_REL_ARM_BRANCH24T")
#pragma pop_macro("IMAGE_REL_ARM_BRANCH24")
#pragma pop_macro("IMAGE_REL_ARM_BRANCH20T")
#pragma pop_macro("IMAGE_REL_ARM_BRANCH11")
#pragma pop_macro("IMAGE_REL_ARM_BLX24")
#pragma pop_macro("IMAGE_REL_ARM_BLX23T")
#pragma pop_macro("IMAGE_REL_ARM_BLX11")
#pragma pop_macro("IMAGE_REL_ARM_ADDR32NB")
#pragma pop_macro("IMAGE_REL_ARM_ADDR32")
#pragma pop_macro("IMAGE_REL_ARM_ABSOLUTE")
#pragma pop_macro("IMAGE_REL_ARM64_TOKEN")
#pragma pop_macro("IMAGE_REL_ARM64_SECTION")
#pragma pop_macro("IMAGE_REL_ARM64_SECREL_LOW12L")
#pragma pop_macro("IMAGE_REL_ARM64_SECREL_LOW12A")
#pragma pop_macro("IMAGE_REL_ARM64_SECREL_HIGH12A")
#pragma pop_macro("IMAGE_REL_ARM64_SECREL")
#pragma pop_macro("IMAGE_REL_ARM64_REL32")
#pragma pop_macro("IMAGE_REL_ARM64_REL21")
#pragma pop_macro("IMAGE_REL_ARM64_PAGEOFFSET_12L")
#pragma pop_macro("IMAGE_REL_ARM64_PAGEOFFSET_12A")
#pragma pop_macro("IMAGE_REL_ARM64_PAGEBASE_REL21")
#pragma pop_macro("IMAGE_REL_ARM64_BRANCH26")
#pragma pop_macro("IMAGE_REL_ARM64_BRANCH19")
#pragma pop_macro("IMAGE_REL_ARM64_BRANCH14")
#pragma pop_macro("IMAGE_REL_ARM64_ADDR64")
#pragma pop_macro("IMAGE_REL_ARM64_ADDR32NB")
#pragma pop_macro("IMAGE_REL_ARM64_ADDR32")
#pragma pop_macro("IMAGE_REL_ARM64_ABSOLUTE")
#pragma pop_macro("IMAGE_REL_AMD64_TOKEN")
#pragma pop_macro("IMAGE_REL_AMD64_SSPAN32")
#pragma pop_macro("IMAGE_REL_AMD64_SREL32")
#pragma pop_macro("IMAGE_REL_AMD64_SECTION")
#pragma pop_macro("IMAGE_REL_AMD64_SECREL7")
#pragma pop_macro("IMAGE_REL_AMD64_SECREL")
#pragma pop_macro("IMAGE_REL_AMD64_REL32_5")
#pragma pop_macro("IMAGE_REL_AMD64_REL32_4")
#pragma pop_macro("IMAGE_REL_AMD64_REL32_3")
#pragma pop_macro("IMAGE_REL_AMD64_REL32_2")
#pragma pop_macro("IMAGE_REL_AMD64_REL32_1")
#pragma pop_macro("IMAGE_REL_AMD64_REL32")
#pragma pop_macro("IMAGE_REL_AMD64_PAIR")
#pragma pop_macro("IMAGE_REL_AMD64_ADDR64")
#pragma pop_macro("IMAGE_REL_AMD64_ADDR32NB")
#pragma pop_macro("IMAGE_REL_AMD64_ADDR32")
#pragma pop_macro("IMAGE_REL_AMD64_ABSOLUTE")
#pragma pop_macro("IMAGE_LOAD_CONFIG_DIRECTORY64")
#pragma pop_macro("IMAGE_LOAD_CONFIG_DIRECTORY32")
#pragma pop_macro("IMAGE_FILE_UP_SYSTEM_ONLY")
#pragma pop_macro("IMAGE_FILE_SYSTEM")
#pragma pop_macro("IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP")
#pragma pop_macro("IMAGE_FILE_RELOCS_STRIPPED")
#pragma pop_macro("IMAGE_FILE_NET_RUN_FROM_SWAP")
#pragma pop_macro("IMAGE_FILE_MACHINE_WCEMIPSV2")
#pragma pop_macro("IMAGE_FILE_MACHINE_UNKNOWN")
#pragma pop_macro("IMAGE_FILE_MACHINE_THUMB")
#pragma pop_macro("IMAGE_FILE_MACHINE_SH5")
#pragma pop_macro("IMAGE_FILE_MACHINE_SH4")
#pragma pop_macro("IMAGE_FILE_MACHINE_SH3DSP")
#pragma pop_macro("IMAGE_FILE_MACHINE_SH3")
#pragma pop_macro("IMAGE_FILE_MACHINE_RISCV64")
#pragma pop_macro("IMAGE_FILE_MACHINE_RISCV32")
#pragma pop_macro("IMAGE_FILE_MACHINE_RISCV128")
#pragma pop_macro("IMAGE_FILE_MACHINE_R4000")
#pragma pop_macro("IMAGE_FILE_MACHINE_POWERPCFP")
#pragma pop_macro("IMAGE_FILE_MACHINE_POWERPC")
#pragma pop_macro("IMAGE_FILE_MACHINE_MIPSFPU16")
#pragma pop_macro("IMAGE_FILE_MACHINE_MIPSFPU")
#pragma pop_macro("IMAGE_FILE_MACHINE_MIPS16")
#pragma pop_macro("IMAGE_FILE_MACHINE_M32R")
#pragma pop_macro("IMAGE_FILE_MACHINE_IA64")
#pragma pop_macro("IMAGE_FILE_MACHINE_I386")
#pragma pop_macro("IMAGE_FILE_MACHINE_EBC")
#pragma pop_macro("IMAGE_FILE_MACHINE_ARMNT")
#pragma pop_macro("IMAGE_FILE_MACHINE_ARM64X")
#pragma pop_macro("IMAGE_FILE_MACHINE_ARM64EC")
#pragma pop_macro("IMAGE_FILE_MACHINE_ARM64")
#pragma pop_macro("IMAGE_FILE_MACHINE_ARM")
#pragma pop_macro("IMAGE_FILE_MACHINE_AMD64")
#pragma pop_macro("IMAGE_FILE_MACHINE_AM33")
#pragma pop_macro("IMAGE_FILE_LOCAL_SYMS_STRIPPED")
#pragma pop_macro("IMAGE_FILE_LINE_NUMS_STRIPPED")
#pragma pop_macro("IMAGE_FILE_LARGE_ADDRESS_AWARE")
#pragma pop_macro("IMAGE_FILE_EXECUTABLE_IMAGE")
#pragma pop_macro("IMAGE_FILE_DLL")
#pragma pop_macro("IMAGE_FILE_DEBUG_STRIPPED")
#pragma pop_macro("IMAGE_FILE_BYTES_REVERSED_LO")
#pragma pop_macro("IMAGE_FILE_BYTES_REVERSED_HI")
#pragma pop_macro("IMAGE_FILE_AGGRESSIVE_WS_TRIM")
#pragma pop_macro("IMAGE_FILE_32BIT_MACHINE")
#pragma pop_macro("IMAGE_DYNAMIC_RELOCATION_GUARD_SWITCHTABLE_BRANCH")
#pragma pop_macro("IMAGE_DYNAMIC_RELOCATION_GUARD_RF_PROLOGUE")
#pragma pop_macro("IMAGE_DYNAMIC_RELOCATION_GUARD_RF_EPILOGUE")
#pragma pop_macro("IMAGE_DYNAMIC_RELOCATION_GUARD_INDIR_CONTROL_TRANSFER")
#pragma pop_macro("IMAGE_DYNAMIC_RELOCATION_GUARD_IMPORT_CONTROL_TRANSFER")
#pragma pop_macro("IMAGE_DYNAMIC_RELOCATION_ARM64X")
#pragma pop_macro("IMAGE_DVRT_ARM64X_FIXUP_TYPE_ZEROFILL")
#pragma pop_macro("IMAGE_DVRT_ARM64X_FIXUP_TYPE_VALUE")
#pragma pop_macro("IMAGE_DVRT_ARM64X_FIXUP_TYPE_DELTA")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_WDM_DRIVER")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_TERMINAL_SERVER_AWARE")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_NX_COMPAT")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_NO_SEH")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_NO_ISOLATION")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_NO_BIND")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_HIGH_ENTROPY_VA")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_GUARD_CF")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_FORCE_INTEGRITY")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_EX_HOTPATCH_COMPATIBLE")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_EX_FORWARD_CFI_COMPAT")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_EX_CET_SET_CONTEXT_IP_VALIDATION_RELAXED_MODE")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_EX_CET_RESERVED_2")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_EX_CET_RESERVED_1")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_EX_CET_DYNAMIC_APIS_ALLOW_IN_PROC_ONLY")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_EX_CET_COMPAT_STRICT_MODE")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_EX_CET_COMPAT")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_DYNAMIC_BASE")
#pragma pop_macro("IMAGE_DLL_CHARACTERISTICS_APPCONTAINER")
#pragma pop_macro("IMAGE_DEBUG_TYPE_VC_FEATURE")
#pragma pop_macro("IMAGE_DEBUG_TYPE_UNKNOWN")
#pragma pop_macro("IMAGE_DEBUG_TYPE_RESERVED10")
#pragma pop_macro("IMAGE_DEBUG_TYPE_REPRO")
#pragma pop_macro("IMAGE_DEBUG_TYPE_POGO")
#pragma pop_macro("IMAGE_DEBUG_TYPE_OMAP_TO_SRC")
#pragma pop_macro("IMAGE_DEBUG_TYPE_OMAP_FROM_SRC")
#pragma pop_macro("IMAGE_DEBUG_TYPE_MPX")
#pragma pop_macro("IMAGE_DEBUG_TYPE_MISC")
#pragma pop_macro("IMAGE_DEBUG_TYPE_ILTCG")
#pragma pop_macro("IMAGE_DEBUG_TYPE_FPO")
#pragma pop_macro("IMAGE_DEBUG_TYPE_FIXUP")
#pragma pop_macro("IMAGE_DEBUG_TYPE_EX_DLLCHARACTERISTICS")
#pragma pop_macro("IMAGE_DEBUG_TYPE_EXCEPTION")
#pragma pop_macro("IMAGE_DEBUG_TYPE_COFF")
#pragma pop_macro("IMAGE_DEBUG_TYPE_CODEVIEW")
#pragma pop_macro("IMAGE_DEBUG_TYPE_CLSID")
#pragma pop_macro("IMAGE_DEBUG_TYPE_BORLAND")
#pragma pop_macro("IMAGE_COMDAT_SELECT_SAME_SIZE")
#pragma pop_macro("IMAGE_COMDAT_SELECT_NODUPLICATES")
#pragma pop_macro("IMAGE_COMDAT_SELECT_NEWEST")
#pragma pop_macro("IMAGE_COMDAT_SELECT_LARGEST")
#pragma pop_macro("IMAGE_COMDAT_SELECT_EXACT_MATCH")
#pragma pop_macro("IMAGE_COMDAT_SELECT_ASSOCIATIVE")
#pragma pop_macro("IMAGE_COMDAT_SELECT_ANY")
#pragma pop_macro("IMAGE_AUX_SYMBOL_TYPE_TOKEN_DEF")
#endif
