/*************************************************************
 * UlteSoft WebAssembly Virtual Machine (Version 2)          *
 * Copyright (c) 2025-present UlteSoft. All rights reserved. *
 * Licensed under the APL-2.0 License (see LICENSE file).    *
 *************************************************************/
// Included after the actual LLVM state and original reference primitive.
// Consume one event from the successful sole typed walk. No raw Wasm span,
// opcode reader, LEB decoder or repeat semantic stack walk enters lowering.
[[nodiscard]] inline bool try_emit_runtime_local_func_llvm_jit_decoded_ref_is_null(
    runtime_local_func_llvm_jit_emit_state_t& state,
    ::uwvm2::validation::standard::wasm3::core3_ref_is_null_event const& event) noexcept
{
    namespace t = ::uwvm2::parser::wasm::standard::wasm3::type;
    if(!state.valid || state.ir_builder == nullptr || state.llvm_context_holder == nullptr ||
       state.llvm_module == nullptr || state.llvm_function == nullptr ||
       state.local_func_storage_ptr == nullptr || state.control_stack.empty() ||
       state.current_wasm_op_offset == SIZE_MAX || event.result_type.kind != t::value_kind::i32 ||
       event.input_type.kind != t::value_kind::reference) { return false; }
    // [owned LLVM control frames ... last] end
    // [safe] empty() proved back(); no guest input pointer is inspected.
    // 0xd1 is outside the existing sealed_pure family. Keep the original
    // generic retirement before any root escape or physical SSA pop/push.
#if defined(UWVM_EXPERIMENTAL_SEALED_COMPACT_CURSOR) && UWVM_EXPERIMENTAL_SEALED_COMPACT_CURSOR == 1
    if(state.control_stack.back().is_reachable &&
       (!snapshot_runtime_local_func_llvm_jit_gc_roots(state) || !sealed_compact_codegen::retire(state))) { return false; }
#endif
    // current_wasm_op_offset is already assigned by the fused dispatcher;
    // use the same existing deduplicating provenance/debug hooks without
    // forming, advancing, subtracting or dereferencing any bytecode pointer.
    if(!emit_runtime_local_func_llvm_jit_native_provenance(state, state.current_wasm_op_offset)) { return false; }
    if(state.pending_numeric_plan != nullptr && !pending_numeric_primary_opcode(0xd1u)) { return false; }
    if(!emit_runtime_local_func_llvm_jit_instruction_debug_safe_point(state)) { return false; }
    if(!state.control_stack.back().is_reachable || state.unreachable_control_depth != 0uz) { return true; }
    // A reachable successful transition must have consumed a real reference;
    // synthetic Bot reaches the unreachable skip above, never a physical pop.
    if(!event.concrete_input || state.operand_stack.empty()) { return false; }
    // [owned SSA descriptors ...][reference] end
    // [safe                                ] empty() proves back(); copy
    // before pop_back retires its original slot. No borrowed entry survives.
    auto const reference{state.operand_stack.back()};
    state.operand_stack.pop_back();
    auto const carrier{get_runtime_wasm_value_type_encoding(reference.type)};
    // Existing physical SSA contract, not another Wasm typing pass. Match the
    // checked DATA's actual carrier when known; target ABI determines width.
    if((carrier != 0x70u && carrier != 0x6fu && carrier != 0x69u) || reference.value == nullptr ||
       (!event.input_unknown && carrier != event.input_carrier)) { return false; }
    auto result{emit_llvm_jit_ref_is_null(*state.ir_builder, reference.value, state.llvm_module->getDataLayout().isLittleEndian())};
    if(result == nullptr) { return false; }
    // Original primitive and i32 physical push; no additional guest memory
    // access/check is generated by retaining exact source type in the event.
    state.operand_stack.push_back({.type = runtime_operand_stack_value_type::i32, .value = result});
    return true;
}
