#pragma once
// Included lexically inside the existing INT lazy details namespace. Only the
// actual fused single-function translator can mint this cold admission owner.
template<::uwvm2::runtime::compiler::uwvm_int::optable::uwvm_interpreter_translate_option_t Option>
inline unsigned char checked_ring_layout_identity{};

class checked_register_ring_admission final
{
    struct source_record { void const* code{}; void const* signature{}; };
    runtime_module_storage_t const* module_{};
    ::std::uint_least64_t generation_{};
    ::std::size_t module_id_{};
    unsigned char const* layout_{};
    ::std::vector<source_record> functions_{};
    bool complete_{};
    checked_register_ring_admission(runtime_module_storage_t const& module, ::std::size_t id, unsigned char const* layout)
        : module_{::std::addressof(module)}, generation_{::uwvm2::runtime::lib::observe_compiler_runtime_generation_host_api()},
          module_id_{id}, layout_{layout} {}
public:
    static constexpr ::std::size_t maximum_retained_opbytes{128uz * 1024uz * 1024uz};
    static constexpr ::std::size_t maximum_function_opbytes{8uz * 1024uz * 1024uz};
    static constexpr ::std::size_t maximum_functions{65536uz};
    checked_register_ring_admission(checked_register_ring_admission const&) = delete;
    checked_register_ring_admission& operator=(checked_register_ring_admission const&) = delete;

    template<::uwvm2::runtime::compiler::uwvm_int::optable::uwvm_interpreter_translate_option_t Option>
    [[nodiscard]] bool matches_function(runtime_module_storage_t const& module, ::std::size_t module_id, ::std::size_t index) const noexcept
    {
        if(!complete_ || module_ != ::std::addressof(module) || module_id_ != module_id ||
           generation_ != ::uwvm2::runtime::lib::observe_compiler_runtime_generation_host_api() ||
           layout_ != ::std::addressof(checked_ring_layout_identity<Option>) ||
           functions_.size() != module.local_defined_function_vec_storage.size() || index >= functions_.size()) { return false; }
        // [actual pinned local records ... size] | end
        // [safe: index<size above             ] | one-past not read
        auto const& actual{module.local_defined_function_vec_storage.index_unchecked(index)};
        return actual.wasm_code_ptr == functions_[index].code && actual.function_type_ptr == functions_[index].signature;
    }

    template<::uwvm2::runtime::compiler::uwvm_int::optable::uwvm_interpreter_translate_option_t Option>
    [[nodiscard]] static ::std::unique_ptr<checked_register_ring_admission> admit(runtime_module_storage_t const& module,
        lazy_module_storage_t& storage, ::uwvm2::runtime::compiler::uwvm_int::optable::compile_option options,
        parser_feature_parameter_t const* features, ::uwvm2::validation::error::code_validation_error_impl& error) UWVM_THROWS
    {
        ::std::unique_ptr<checked_register_ring_admission> pending{new checked_register_ring_admission{
            module, options.curr_wasm_id, ::std::addressof(checked_ring_layout_identity<Option>)}};
        auto const count{module.local_defined_function_vec_storage.size()};
        bool exhausted{count > maximum_functions};
        if(!exhausted) { pending->functions_.resize(count); }
        ::std::size_t retained{};
        for(::std::size_t index{}; index != count; ++index)
        {
            // Original register-ring translator and its existing fixup ownership:
            // validation and emission happen together. The saved stream is never
            // generated by a separate pure validator or replayed on first call.
            ::uwvm2::runtime::compiler::uwvm_int::compile_all_from_uwvm::details::compile_all_from_uwvm_local_func<Option>(
                module, options, storage.compiled, index, features, error);
            auto& actual{storage.compiled.local_funcs.index_unchecked(index)};
            auto const bytes{actual.op.operands.size()};
            if(bytes > maximum_function_opbytes || retained > maximum_retained_opbytes || bytes > maximum_retained_opbytes - retained)
            { exhausted = true; }
            if(exhausted)
            {
                // Quota is on retained dispatch bytes only. Existing one-function
                // translator scratch and EH metadata are not an RSS claim. Later
                // bodies still run the same authoritative checks before reporting
                // a distinct compiler-resource failure; no partial code publishes.
                actual.op = {};
            }
            else
            {
                retained += bytes;
                auto const& original{module.local_defined_function_vec_storage.index_unchecked(index)};
                pending->functions_[index] = {original.wasm_code_ptr, original.function_type_ptr};
            }
        }
        aggregate_lazy_local_function_storage(storage.compiled);
        if(exhausted)
        {
            ::fast_io::io::perr(::uwvm2::uwvm::io::u8log_output,
                ::fast_io::mnp::cond(::uwvm2::uwvm::utils::ansies::put_color, UWVM_COLOR_U8_RST_ALL_AND_SET_WHITE),
                u8"uwvm: ", ::fast_io::mnp::cond(::uwvm2::uwvm::utils::ansies::put_color, UWVM_COLOR_U8_LT_RED),
                u8"[fatal] ", ::fast_io::mnp::cond(::uwvm2::uwvm::utils::ansies::put_color, UWVM_COLOR_U8_WHITE),
                u8"INT lazy checked dispatch artifact resource quota exceeded. (runtime)\n\n",
                ::fast_io::mnp::cond(::uwvm2::uwvm::utils::ansies::put_color, UWVM_COLOR_U8_RST_ALL));
            ::fast_io::fast_terminate();
        }
        pending->complete_ = error.err_code == code_validation_error_code::ok;
        return pending;
    }
};
