#!/usr/bin/env python3
"""Run current Core 3 typed-reference grammar against the real LLVM JIT.

The fixtures are generated by 0013.uwvm_int/run_call_ref_typed_core3.py;
their text is checked here so a stale Wasm cannot silently pass this matrix.
Run inside the required Linux 64 GiB / 20-CPU cgroup only.
"""

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import resource
import subprocess


def load_cases(root):
    path = root / 'test/0013.uwvm_int/run_call_ref_typed_core3.py'
    spec = importlib.util.spec_from_file_location('typed_core3_cases', path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.CASES


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('output', type=Path)
    parser.add_argument('--uwvm', type=Path, required=True)
    parser.add_argument('--fixtures', type=Path, required=True)
    parser.add_argument('--wasmtime', type=Path, required=True)
    parser.add_argument('--wasm-tools', type=Path)
    parser.add_argument('--ros', action='store_true')
    parser.add_argument('--only-case', action='append')
    parser.add_argument('--only-mode', action='append')
    parser.add_argument('--guard', type=Path)
    parser.add_argument('--source-root', type=Path)
    args = parser.parse_args()
    root = args.source_root or Path(__file__).resolve().parents[2]
    subprocess.run(['bash', str(args.guard or root / 'tools/ci/require_wasm3_test_cgroup.sh')], check=True)
    resource.setrlimit(resource.RLIMIT_CORE, (0, 0))
    cases = load_cases(root)
    if args.only_case:
        unknown = set(args.only_case) - cases.keys()
        if unknown:
            parser.error(f'unknown cases: {sorted(unknown)}')
        cases = {name: cases[name] for name in args.only_case}
    if any(outcome == 'ok-wasm-tools-validation' for outcome, _ in cases.values()) and not args.wasm_tools:
        parser.error('--wasm-tools is required for cases whose Wasmtime compiler cannot execute the valid module')
    modes = {'jit-full': ['-Raot']} if args.ros else {
        'jit-full': ['-Rcc', 'jit', '-Rcm', 'full'],
        'jit-lazy': ['-Rcc', 'jit', '-Rcm', 'lazy'],
        'tiered-lazy': ['-Rcc', 'tiered', '-Rcm', 'lazy', '-Rct', '0'],
    }
    if args.only_mode:
        unknown = set(args.only_mode) - modes.keys()
        if unknown:
            parser.error(f'unknown modes: {sorted(unknown)}')
        modes = {name: modes[name] for name in args.only_mode}
    args.output.mkdir(parents=True, exist_ok=False)
    rows = []
    for name, (outcome, source) in cases.items():
        gc_flags = ['-WFE-gc'] if name.startswith('rec-') else []
        function_reference_flags = [] if name == 'rec-singleton-direct' else ['-WFE-function-references']
        wat = args.fixtures / (name + '.wat')
        wasm = args.fixtures / (name + '.wasm')
        if wat.read_text() != source + '\n' or not wasm.is_file():
            raise RuntimeError(f'fixture differs from current Core 3 grammar: {name}')
        commands = {'wasm-tools-validation': [str(args.wasm_tools), 'validate', '--features', 'all', str(wasm)]} if \
            outcome == 'ok-wasm-tools-validation' else {'wasmtime': [str(args.wasmtime), '-C', 'cache=n',
            '-W', 'function-references=y', '-W', 'tail-call=y', str(wasm)]}
        commands.update({mode: [str(args.uwvm), *flags,
            *function_reference_flags, *gc_flags, '-WFE-tail-call', '--run', str(wasm)]
            for mode, flags in modes.items()})
        for mode, command in commands.items():
            result = subprocess.run(command, capture_output=True, timeout=120)
            log = (result.stdout + result.stderr).decode(errors='replace')
            (args.output / f'{name}-{mode}.log').write_text(log)
            expected_success = outcome in ('ok', 'ok-wasm-tools-validation')
            passed = (result.returncode == 0) == expected_success
            if outcome == 'null reference':
                passed = passed and 'null reference' in log.lower()
            if outcome == 'validation':
                diagnostic = log.lower()
                rich_element_mismatch = ('parsing error' in diagnostic and
                    'element segment reference type' in diagnostic and 'does not match' in diagnostic)
                passed = passed and (rich_element_mismatch or any(part in diagnostic for part in
                    ('validation error', 'type mismatch', 'invalid input',
                     'illegal type index', 'type index out of bounds', 'unknown type')))
            rows.append({'case': name, 'mode': mode, 'outcome': outcome,
                'passed': passed, 'exit': result.returncode, 'command': command})
            (args.output / 'runs.json').write_text(json.dumps(rows, indent=2) + '\n')
    summary = {'passed': all(row['passed'] for row in rows), 'checks': len(rows),
        'product': 'uwvm2-ros' if args.ros else 'uwvm2',
        'binary_sha256': hashlib.sha256(args.uwvm.read_bytes()).hexdigest(),
        'runner_sha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}
    (args.output / 'summary.json').write_text(json.dumps(summary, indent=2) + '\n')
    print(f"Core 3 typed-reference JIT: {sum(row['passed'] for row in rows)}/{len(rows)} checks",
        flush=True)
    if not summary['passed']:
        for row in rows:
            if not row['passed']:
                print(f"FAIL {row['case']} {row['mode']}: exit={row['exit']}", flush=True)
        raise SystemExit(1)


if __name__ == '__main__':
    main()
