;; Core 3.0 event fixture, not a legacy-only debugger smoke test. Official
;; validation and both products must use the same generated bytes and flags.
(module
  (type $node (sub (struct (field (mut i32)) (field (mut (ref null $node))))))
  (type $bytes (array (mut i8)))
  (type $fn (func (param i32) (result i32)))
  (memory $wide i64 1 2)
  (memory $shared 1 1 shared)
  (table $functions i64 2 4 (ref null $fn))
  (tag $error (param i32))
  (func $leaf (type $fn) (param i32) (result i32)
    local.get 0 i32.const 1 i32.add)
  (func $tail (type $fn) (param i32) (result i32)
    local.get 0 return_call $leaf)
  (elem declare func $leaf)
  (func (export "_start") (local $root (ref null $node))
    i32.const 7 ref.null $node struct.new $node local.set $root
    local.get $root struct.get $node 0 drop
    i32.const 3 i32.const 8 array.new $bytes array.len drop
    i64.const 0 i32.const 123 i32.store $wide
    i64.const 0 i32.load $wide drop
    i32.const 0 i32.atomic.load $shared drop
    atomic.fence
    i64.const 0 ref.func $leaf table.set $functions
    i32.const 9 i64.const 0 call_indirect $functions (type $fn) drop
    i32.const 9 call $tail drop
    i64.const 0 v128.load $wide drop
    v128.const i32x4 0 0 0 0 v128.const i32x4 0 0 0 0
    i8x16.relaxed_swizzle drop
    block $caught (result i32)
      try_table (catch $error $caught)
        i32.const 99 throw $error
      end
      unreachable
    end
    drop))
