#!/usr/bin/env bash
set -euo pipefail
source "$(dirname -- "${BASH_SOURCE[0]}")/require_wasm3_test_cgroup.sh"
cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.."
out=${1:?output directory}
fixtures=${2:?directory generated by multi_memory_cases.py}
mkdir -p "$out"
out=$(cd "$out" && pwd)
cxx=${CXX:-clang++}
runtime=${UWVM_TEST_RUNTIME_OBJECT:?runtime object from the current source build}
deps=${UWVM_TEST_DEPS_ROOT:?extracted dependencies}
flags=(-std=c++26 -stdlib=libc++ -fno-rtti -O1 -g0 -Wno-undefined-inline
    -DUWVM=2 -DUWVM_USE_LLVM_JIT -DUWVM_USE_UWVM_INT -DUWVM_DISABLE_LOCAL_IMPORTED_WASIP1
    -DUWVM_RUNTIME_LLVM_JIT_CACHE_USE_OPENSSL_ED25519
    -I src -I third-parties/fast_io/include -I third-parties/bizwen/include -I third-parties/boost_unordered/include
    -I "$deps/include" -I "$deps/include/x86_64-linux-gnu")
links=(-fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -L "$deps/lib/x86_64-linux-gnu" -lssl -lcrypto -ldl -pthread)
if [[ -n ${UWVM_TEST_ROS_LLVM_BUILD:-} ]]; then
    flags+=(-I "$UWVM_TEST_ROS_LLVM_BUILD/include" -I third-parties/llvm/llvm/include)
    links+=("@$UWVM_TEST_ROS_LLVM_BUILD/consumer-link.rsp")
else
    flags+=(-I "${UWVM_TEST_LLVM_ROOT:?LLVM installation}/include")
    links+=(-L "$UWVM_TEST_LLVM_ROOT/lib" -lLLVM)
fi
ulimit -c 0
for fixture in llvm_jit_wasm3_initializers_ir llvm_jit_wasm3_multi_memory_provider; do
    "$cxx" "${flags[@]}" "test/0014.llvm_jit/$fixture.cc" src/uwvm2/uwvm/host_api.default.cpp "$runtime" "${links[@]}" -o "$out/$fixture" >"$out/$fixture.build.log" 2>&1
done
"$out/llvm_jit_wasm3_multi_memory_provider" >"$out/provider.run.log" 2>&1
for fixture in alternate-memory-selection copy-memory1-to-0 simd-load index-129-memarg; do
    for policy in instruction unwind; do
        "$out/llvm_jit_wasm3_initializers_ir" "$fixtures/$fixture-exec.wasm" "$out/$fixture-$policy.ll" "$policy" >"$out/$fixture-$policy.log" 2>&1
    done
done
echo 'PASS new multi-memory provider execution/bounds and actual scalar/SIMD/copy/high-index LLVM IR'
