name: CI
on:
  pull_request:
    paths-ignore:
      - "documents/**"
      - "**.md"
  push:
    paths-ignore:
      - "documents/**"
      - "**.md"
  workflow_dispatch:

jobs:
  # ---------------------------------------------------------------------------
  x86_64-linux-gnu:
    name: x86_64-linux-gnu (ubuntu-24.04)
    runs-on: ubuntu-24.04 # noble
    strategy:
      matrix:
        mode: ["debug"]
        policies: ["build.sanitizer.address"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/llvm.asc
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main"
          sudo apt-get install clang clang-tools lld xmake

      - name: Native (AVX2 + BMI(2) + PRFCHW) Configure
        run: xmake f -m debug --use-llvm=y --sdk=/usr/lib/llvm-21 -m ${{ matrix.mode }} --policies=${{ matrix.policies }}
      - name: Native (AVX2 + BMI(2) + PRFCHW) Build
        run: xmake b -rv
      - name: Native (AVX2 + BMI(2) + PRFCHW) Check UWVM version
        run: xmake run uwvm --version
      - name: Native (AVX2 + BMI(2) + PRFCHW) Unit tests
        run: xmake test -vD

      # - name: MMX Configure
      #   run: xmake f -m debug --use-llvm=y --sdk=/usr/lib/llvm-21 -m ${{ matrix.mode }} --policies=${{ matrix.policies }} --march=none --cxflags="-mno-sse"
      # - name: MMX Build
      #   run: xmake b -rv
      # - name: MMX Check UWVM version
      #   run: xmake run uwvm --version
      # - name: MMX Unit tests
      #   run: xmake test -vD

      # - name: SSE Configure
      #   run: xmake f -m debug --use-llvm=y --sdk=/usr/lib/llvm-21 -m ${{ matrix.mode }} --policies=${{ matrix.policies }} --march=none --cxflags="-mno-sse2"
      # - name: SSE Build
      #   run: xmake b -rv
      # - name: SSE Check UWVM version
      #   run: xmake run uwvm --version
      # - name: SSE Unit tests
      #   run: xmake test -vD

      - name: SSE2 Configure
        run: xmake f -m debug --use-llvm=y --sdk=/usr/lib/llvm-21 -m ${{ matrix.mode }} --policies=${{ matrix.policies }} --march=none
      - name: SSE2 Build
        run: xmake b -rv
      - name: SSE2 Check UWVM version
        run: xmake run uwvm --version
      - name: SSE2 Unit tests
        run: xmake test -vD

      - name: SSSE3 Configure
        run: xmake f -m debug --use-llvm=y --sdk=/usr/lib/llvm-21 -m ${{ matrix.mode }} --policies=${{ matrix.policies }} --march=none --cxflags="-mssse3"
      - name: SSSE3 Build
        run: xmake b -rv
      - name: SSSE3 Check UWVM version
        run: xmake run uwvm --version
      - name: SSSE3 Unit tests
        run: xmake test -vD

      - name: SSE4.x + BMI(2) + PRFCHW Configure
        run: xmake f -m debug --use-llvm=y --sdk=/usr/lib/llvm-21 -m ${{ matrix.mode }} --policies=${{ matrix.policies }} --march=none --cxflags="-msse4 -mbmi -mbmi2 -mprfchw"
      - name: SSE4.x + BMI(2) + PRFCHW Build
        run: xmake b -rv
      - name: SSE4.x + BMI(2) + PRFCHW Check UWVM version
        run: xmake run uwvm --version
      - name: SSE4.x + BMI(2) + PRFCHW Unit tests
        run: xmake test -vD

      - name: AVX + BMI(2) + PRFCHW Configure
        run: xmake f -m debug --use-llvm=y --sdk=/usr/lib/llvm-21 -m ${{ matrix.mode }} --policies=${{ matrix.policies }} --march=none --cxflags="-mavx -mbmi -mbmi2 -mprfchw"
      - name: AVX + BMI(2) + PRFCHW Build
        run: xmake b -rv
      - name: AVX + BMI(2) + PRFCHW Check UWVM version
        run: xmake run uwvm --version
      - name: AVX + BMI(2) + PRFCHW Unit tests
        run: xmake test -vD

      # - name: AVX512BW (AVX512F) + BMI(2) + PRFCHW Configure
      #   run: xmake f -m debug --use-llvm=y --sdk=/usr/lib/llvm-21 -m ${{ matrix.mode }} --policies=${{ matrix.policies }} --march=none --cxflags="-mavx512bw -mbmi -mbmi2 -mprfchw"
      # - name: AVX512BW (AVX512F) + BMI(2) + PRFCHW Build
      #   run: xmake b -rv
      # - name: AVX512BW (AVX512F) + BMI(2) + PRFCHW Check UWVM version
      #   run: xmake run uwvm --version
      # - name: AVX512BW (AVX512F) + BMI(2) + PRFCHW Unit tests
      #   run: xmake test -vD

      # - name: AVX512VBVMI(2) (AVX512BW AVX512F) + BMI(2) + PRFCHW Configure
      #   run: xmake f -m debug --use-llvm=y --sdk=/usr/lib/llvm-21 -m ${{ matrix.mode }} --policies=${{ matrix.policies }} --march=none --cxflags="-mavx512vbmi -mavx512vbmi2 -mbmi -mbmi2 -mprfchw"
      # - name: AVX512VBVMI(2) (AVX512BW AVX512F) + BMI(2) + PRFCHW Build
      #   run: xmake b -rv
      # - name: AVX512VBVMI(2) (AVX512BW AVX512F) + BMI(2) + PRFCHW Check UWVM version
      #   run: xmake run uwvm --version
      # - name: AVX512VBVMI(2) (AVX512BW AVX512F) + BMI(2) + PRFCHW Unit tests
      #   run: xmake test -vD

  # ---------------------------------------------------------------------------
  x86_64_apx-linux-gnu:
    if: ${{ !always() }}
    name: x86_64_apx-linux-gnu (ubuntu-24.04)
    runs-on: ubuntu-24.04 # noble
    strategy:
      matrix:
        mode: ["debug"]
        policies: ["build.sanitizer.address"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/llvm.asc
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main"
          sudo apt-get install clang clang-tools lld xmake
      - name: Native (APX) Configure
        run: xmake f -m debug --use-llvm=y --sdk=/usr/lib/llvm-21 -m ${{ matrix.mode }} --policies=${{ matrix.policies }} --march=none --cxflags="-mapxf -mbmi -mbmi2 -mprfchw"
      - name: Native (APX) Build
        run: xmake b -rv
      - name: Native (APX) Check UWVM version
        run: xmake run uwvm --version
      - name: Native (APX) Unit tests
        run: xmake test -vD

  # ---------------------------------------------------------------------------
  x86_64-windows-gnu:
    if: ${{ !always() }} # Remove it once update to LLVM21
    name: x86_64-windows-gnu (MINGW ${{ matrix.env.name }})
    runs-on: windows-latest
    strategy:
      matrix:
        env:
          - name: "CLANG64"
            prefix: mingw-w64-clang-x86_64
          - name: "CLANGARM64"
            prefix: mingw-w64-clang-aarch64
        mode: ["debug"]
        policies: ["build.sanitizer.address"]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.env.name }}
          update: true
          install: |
            ${{ matrix.env.prefix }}-cc
            ${{ matrix.env.prefix }}-xmake
      - name: Configure
        run: xmake f -p mingw --use-llvm=y -m ${{ matrix.mode }} --policies=${{ matrix.policies }}
      - name: Build
        run: xmake b -rv
      - name: Check UWVM version
        run: xmake run uwvm --version
      - name: Unit tests
        run: xmake test -vD

  # ---------------------------------------------------------------------------
  x86_64-freebsd14:
    if: ${{ !always() }} # Remove it once support "202411L: Structured bindings can introduce a pack"
    name: x86_64-freebsd14
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: ["debug"]
        policies: ["build.sanitizer.address"]
    steps:
      - uses: actions/checkout@v4
      - uses: cross-platform-actions/action@v0.27.0
        with:
          operating_system: freebsd
          version: "14.2"
          run: |
            sudo pkg install -y llvm-devel xmake-io
            xmake f -m debug --use-llvm=y -m ${{ matrix.mode }} --policies=${{ matrix.policies }}
            xmake b -rv
            xmake run uwvm --version
            xmake test -vD
